#!/usr/bin/env python3
"""
Generate and validate the Battle Royale trainer map section lookup table.

Usage:
    python3 tools/trainer_map_sections.py          # regenerate table from map data
    python3 tools/trainer_map_sections.py --check   # validate table against map data
    python3 tools/trainer_map_sections.py --fix     # validate and auto-correct mismatches

The table maps trainer IDs to region map section IDs for use in the
Battle Royale tracker UI. It is a flat array indexed by trainer ID.
"""

import json
import os
import re
import sys

BASE_DIR = os.path.join(os.path.dirname(__file__), '..')
MAPS_DIR = os.path.join(BASE_DIR, 'data', 'maps')
OPPONENTS_H = os.path.join(BASE_DIR, 'include', 'constants', 'opponents.h')
REGION_MAP_H = os.path.join(BASE_DIR, 'include', 'constants', 'region_map_sections.h')
TABLE_FILE = os.path.join(BASE_DIR, 'src', 'data', 'battle_royale', 'trainer_map_sections.h')

BR_FLAG = 'FLAG_HIDE_BATTLE_ROYALE_TRAINERS'
TRAINERBATTLE_RE = re.compile(r'trainerbattle_\w+\s+(TRAINER_\w+)')
DEFINE_TRAINER_RE = re.compile(r'#define\s+(TRAINER\w+)\s+(\d+)')
DEFINE_MAPSEC_RE = re.compile(r'#define\s+(MAPSEC_\w+)\s+(0x[0-9A-Fa-f]+|\d+)')


def parse_trainer_ids():
    ids = {}
    with open(OPPONENTS_H) as f:
        for line in f:
            m = DEFINE_TRAINER_RE.match(line.strip())
            if m:
                ids[m.group(1)] = int(m.group(2))
    return ids


def parse_mapsec_values():
    """Parse MAPSEC_* constants. Supports both #define and enum formats."""
    mapsecs = {}
    in_enum = False
    counter = 0
    with open(REGION_MAP_H) as f:
        for line in f:
            # #define format (Legacy)
            m = DEFINE_MAPSEC_RE.match(line.strip())
            if m:
                val_str = m.group(2)
                val = int(val_str, 16) if val_str.startswith('0x') else int(val_str)
                mapsecs[m.group(1)] = val
                continue
            # enum format (pokeemerald)
            stripped = line.strip().rstrip(',')
            if 'enum {' in line or 'enum{' in line:
                in_enum = True
                counter = 0
                continue
            if in_enum:
                if stripped == '};':
                    break
                if stripped.startswith('//') or stripped == '':
                    continue
                if '=' in stripped:
                    parts = stripped.split('=')
                    mapsecs[parts[0].strip()] = int(parts[1].strip())
                    counter = int(parts[1].strip()) + 1
                else:
                    mapsecs[stripped] = counter
                    counter += 1
    return mapsecs


def read_table():
    with open(TABLE_FILE) as f:
        content = f.read()
    nums = re.findall(r'\b(\d+)\b', content.split('{')[1].split('}')[0])
    return [int(n) for n in nums]


def write_table(table):
    count = len(table)
    lines = ['/* Auto-generated by tools/trainer_map_sections.py. Do not edit. */']
    lines.append('')
    lines.append('static const u8 sTrainerMapSections[%d] = {' % count)
    for i in range(0, count, 16):
        chunk = table[i:i + 16]
        vals = ', '.join('%3d' % v for v in chunk)
        lines.append('    %s,' % vals)
    lines.append('};')
    lines.append('')
    os.makedirs(os.path.dirname(TABLE_FILE), exist_ok=True)
    with open(TABLE_FILE, 'w') as f:
        f.write('\n'.join(lines))


def build_trainer_mapsec_map(mapsec_values):
    """Scan all map scripts and return trainer_name -> mapsec_name mapping."""
    trainer_to_mapsec = {}
    for map_name in sorted(os.listdir(MAPS_DIR)):
        map_json_path = os.path.join(MAPS_DIR, map_name, 'map.json')
        scripts_path = os.path.join(MAPS_DIR, map_name, 'scripts.inc')
        if not os.path.isfile(map_json_path) or not os.path.isfile(scripts_path):
            continue
        with open(map_json_path) as f:
            data = json.load(f)
        mapsec_name = data.get('region_map_section', '')
        if not mapsec_name or mapsec_name not in mapsec_values:
            continue
        with open(scripts_path) as f:
            script_text = f.read()
        for m in TRAINERBATTLE_RE.finditer(script_text):
            name = m.group(1)
            if name not in trainer_to_mapsec:
                trainer_to_mapsec[name] = mapsec_name
    return trainer_to_mapsec


def build_br_trainer_mapsec_map(mapsec_values):
    """Like build_trainer_mapsec_map but restricted to FLAG_HIDE_BATTLE_ROYALE_TRAINERS NPCs."""
    placements = {}
    for map_name in sorted(os.listdir(MAPS_DIR)):
        map_json_path = os.path.join(MAPS_DIR, map_name, 'map.json')
        scripts_path = os.path.join(MAPS_DIR, map_name, 'scripts.inc')
        if not os.path.isfile(map_json_path) or not os.path.isfile(scripts_path):
            continue
        with open(map_json_path) as f:
            data = json.load(f)
        mapsec_name = data.get('region_map_section', '')
        if not mapsec_name or mapsec_name not in mapsec_values:
            continue
        br_scripts = {obj.get('script', '') for obj in data.get('object_events', [])
                      if obj.get('flag') == BR_FLAG}
        if not br_scripts:
            continue
        with open(scripts_path) as f:
            script_text = f.read()
        current_label = None
        for line in script_text.splitlines():
            stripped = line.strip()
            if stripped.endswith('::'):
                current_label = stripped[:-2]
            elif current_label in br_scripts:
                m = TRAINERBATTLE_RE.search(stripped)
                if m:
                    placements[m.group(1)] = (mapsec_name, map_name)
    return placements


def cmd_generate():
    trainer_ids, trainers_count = {}, 0
    raw = parse_trainer_ids()
    trainer_ids = raw
    trainers_count = raw.get('TRAINERS_COUNT', 0)

    mapsec_values = parse_mapsec_values()
    mapsec_none = mapsec_values.get('MAPSEC_NONE', 0)
    trainer_to_mapsec = build_trainer_mapsec_map(mapsec_values)

    table = [mapsec_none] * trainers_count
    mapped_count = 0
    for trainer_name, mapsec_name in trainer_to_mapsec.items():
        if trainer_name in trainer_ids and mapsec_name in mapsec_values:
            idx = trainer_ids[trainer_name]
            if 0 < idx < trainers_count:
                table[idx] = mapsec_values[mapsec_name]
                mapped_count += 1

    write_table(table)
    print('Generated %s: %d/%d trainer mappings (%d total slots)' % (
        TABLE_FILE, mapped_count, len(trainer_to_mapsec), trainers_count))
    return 0


def cmd_check(fix=False):
    trainer_ids = parse_trainer_ids()
    mapsec_values = parse_mapsec_values()
    mapsec_names = {v: k for k, v in mapsec_values.items()}
    table = read_table()
    placements = build_br_trainer_mapsec_map(mapsec_values)

    mismatches = []
    for trainer_name, (expected_mapsec_name, map_name) in sorted(placements.items()):
        if trainer_name not in trainer_ids:
            print('WARNING: %s not found in opponents.h' % trainer_name)
            continue
        tid = trainer_ids[trainer_name]
        if tid >= len(table):
            print('WARNING: %s (ID %d) out of table bounds' % (trainer_name, tid))
            continue
        expected = mapsec_values[expected_mapsec_name]
        actual = table[tid]
        if actual != expected:
            actual_name = mapsec_names.get(actual, 'UNKNOWN(%d)' % actual)
            mismatches.append((trainer_name, tid, map_name, expected_mapsec_name, expected, actual_name, actual))

    if not mismatches:
        print('OK: All %d Battle Royale trainer placements match the table.' % len(placements))
        return 0

    print('Found %d mismatch(es):' % len(mismatches))
    for trainer_name, tid, map_name, expected_name, expected, actual_name, actual in mismatches:
        print('  %s (ID %d) on %s: expected %s (%d), got %s (%d)' % (
            trainer_name, tid, map_name, expected_name, expected, actual_name, actual))

    if fix:
        for _, tid, _, _, expected, _, _ in mismatches:
            table[tid] = expected
        write_table(table)
        print('Fixed %d entries in %s' % (len(mismatches), TABLE_FILE))
        return 0
    else:
        print('Run with --fix to auto-correct.')
        return 1


def main():
    args = sys.argv[1:]
    if '--check' in args:
        return cmd_check(fix=False)
    elif '--fix' in args:
        return cmd_check(fix=True)
    else:
        return cmd_generate()


if __name__ == '__main__':
    sys.exit(main())
